version: "3.9"
services:
  mysql_db:
    env_file:
      - ./app/.env
    container_name: mysql_db
    image: mysql:5.7
    restart: always
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --innodb_force_recovery=0
    volumes:
      - ./app/mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      TZ: America/Sao_Paulo

  api:
    env_file:
      - ./app/.env
    build: ./app
    ports:
      - 8000:8000
    depends_on:
      - mysql_db
    environment:
      TZ: America/Sao_Paulo

networks:
  default:
    driver: bridge
